print("Exercise15")
print("Bio Data")
name=input("Enter your name:")
age=int(input("enter your age:"))
phone=int(input("Enter your contact number:"))
print("---Bio Data---")
print("Name\t:{}\nAge\t:{}\nPhone\t:{}".format(name,age,phone))
print(F"Name\t:{name}\nAge\t:{age}\nPhone\t:{phone}")
print("================================")