print("Exercise7")
print("Full Name Display")
first_name=input("Enter your first name:")
last_name=input("Enter your last name:")
print(first_name,last_name)
print("--------------------")
print("================================")