print("Exercise8")
print("Simple Input Display")
first_number=input("Enter a number:")
second_number=input("Enter a second number:")
print("{}\n{}".format(first_number,second_number))
print(first_number,second_number,sep="\n")
print("================================")