#Exercise1
print("Hello & Name Printer")
name="Aryan"
print(f"Hello \n{name}")
print("================================")

print("Exercise2")
print("Menu Display")
print("===Welcome to Coffee Shop===")
print("1. Espresso $3 \n2. Latte $4\n3.Cappuccino $5")
print("================================")

print("Exercise3")
print("Resume Format")
name="Alice Johnson"
email="alice@example.com"
print("===Resume===")
print(f"Name \t:{name}\nEmail\t:{email}")
print("Skills\t:\n-Java\n-HTML & CSS\n-Problem Solving\nExperience:2 years at XYZ Ltd.")

print("Name\t:{}\nEmail\t:{}".format(name,email))
print("================================")

print("Exercise4")
print("Star Pattern(without loop)")
print("***\n***\n***")
print("================================")

print("Exercise5")
print("Special Characters")
print("@ # $ % ^ & *")
print("================================")

print("Exercise6")
print("Print User Details")
print("Enter Your Details")
name=input("Enter Your Name ")
age=int(input("Enter Your Age "))
city=input("Enter Your City ")
print(f"Name:{name}\nAge:{age}\nCity:{city}")

print("Name:{}\nAge:{}\nCity:{}".format(name,age,city))
print("================================")

print("Exercise7")
print("Full Name Display")
first_name=input("Enter your first name:")
last_name=input("Enter your last name:")
print(first_name,last_name)
print("--------------------")
print("================================")

print("Exercise8")
print("Simple Input Display")
first_number=input("Enter a number:")
second_number=input("Enter a second number:")
print("{}\n{}".format(first_number,second_number))
print(first_number,second_number,sep="\n")
print("================================")

print("Exercise9")
print("Three Inputs Display")
first_number=input("Enter a number:")
second_number=input("Enter a second number:")
third_number=input("Enter third number")
print("{}\n{}\n{}".format(first_number,second_number,third_number))
print(first_number,second_number,third_number,sep="\n")
print("================================")

print("Exercise10")
print("Input and Echo")
city=input("Enter your address")
print("You entered:",city)
print("================================")

print("Exercise11")
print("Greeting Message")
name=input("Enter Your Name")
print(input("Enter Your Stream"))
print("Hello ",name)
print("Welcome to Python")
print(f"Hello {name}\nWelcome to Python")
print("================================")

print("Exercise12")
print("Favorite Things")
food=input("Enter Your Favorite food")
color=input("Enter Your Favorite color")
print(f"I like {food} and my favorite color is {color}")
print("i like {} and my favorite color is {}".format(food,color))
print("================================")

print("Exercise13")
print("College Details")
#college details
college_name=input("Enter Your College name")
Course=input("Enter your course name")
year=int(input("Enter your course year"))
print(f"My college name is {college_name}\nI am pursuing {Course}\nI am in {year} year")
print("College name:{}\nCourse:{}\nYear:{}year".format(college_name,Course,year))'''
print("================================")

print("Exercise14")
print("Email Display")
email=input("Enter your email id:")
print("Your email is:",email)
print(f"Your email is: {email}")
print("Your email is: {}".format(email))
print("================================")

print("Exercise15")
print("Bio Data")
name=input("Enter your name:")
age=int(input("enter your age:"))
phone=int(input("Enter your contact number:"))
print("---Bio Data---")
print("Name\t:{}\nAge\t:{}\nPhone\t:{}".format(name,age,phone))
print(F"Name\t:{name}\nAge\t:{age}\nPhone\t:{phone}")
print("================================")